-- =====================================================================
-- 000 - Tablas base y almacenamiento de imágenes
-- Ejecutar completo en Supabase > SQL Editor, ANTES de 001, SOLO en un proyecto nuevo.
--
-- Los scripts 001 a 018 suponen que ya existen las tablas profiles, peliculas, generos y pelicula_generos (en el proyecto
-- original se crearon a mano desde el panel de Supabase, antes de empezar a numerar los scripts) y el bucket de imágenes.
-- Este script las deja escritas para que cualquiera pueda armar la base desde cero.
--
-- Es seguro ejecutarlo en una base que ya tiene todo: crea solo lo que falta y no modifica nada de lo existente.
--
-- Antes de ejecutarlo, en el panel de Supabase:
--  * Authentication > Providers > Email: desactivar "Confirm email". La aplicación crea la cuenta y su perfil en el mismo
--    paso y necesita la sesión que Supabase devuelve al registrarse.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1) profiles: una fila por cuenta (la crea la aplicación al registrarse; los saldos de puntos y crédito los agrega la 006)
-- ---------------------------------------------------------------------
create table if not exists profiles (
  id                uuid primary key references auth.users (id) on delete cascade,
  email             text not null,
  nombre            text not null,
  apellido          text not null,
  fecha_nacimiento  date not null,
  tipo_sangre       text,
  color_ojos        text,
  dias_vacaciones   int,
  rol               text not null default 'cliente'
                    check (rol in ('cliente', 'admin', 'empleado_entradas', 'empleado_candy')),
  created_at        timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 2) generos, peliculas y su relación muchos a muchos
--    (los precios y los días de preventa de la película los agrega la 008; el precio base está en cada función)
-- ---------------------------------------------------------------------
create table if not exists generos (
  id      int generated by default as identity primary key,
  nombre  text not null unique
);

create table if not exists peliculas (
  id                uuid primary key default gen_random_uuid(),
  nombre            text not null,
  sinopsis          text not null,
  imagen_url        text not null,
  duracion_minutos  int  not null check (duracion_minutos > 0),
  restriccion_edad  int  not null default 0 check (restriccion_edad in (0, 13, 18)),
  fecha_estreno     date not null,
  activa            boolean not null default true,
  destacada         boolean not null default false,
  created_at        timestamptz not null default now()
);

create table if not exists pelicula_generos (
  pelicula_id  uuid not null references peliculas (id) on delete cascade,
  genero_id    int  not null references generos (id)   on delete cascade,
  primary key (pelicula_id, genero_id)
);

-- Géneros de ejemplo: solo si todavía no hay ninguno
insert into generos (nombre)
select g from unnest(array[
  'Acción', 'Animación', 'Aventura', 'Ciencia ficción', 'Comedia', 'Documental',
  'Drama', 'Fantasía', 'Musical', 'Romance', 'Suspenso', 'Terror'
]) as g
where not exists (select 1 from generos);

-- ---------------------------------------------------------------------
-- 3) Almacenamiento de imágenes: un solo bucket público "imagenes" con una carpeta por tema
--    (peliculas/, productos/, combos/). Cualquiera las puede ver; solo las cuentas con sesión pueden subir.
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('imagenes', 'imagenes', true)
on conflict (id) do update set public = true;

do $$
begin
  if not exists (select 1 from pg_policies
                  where schemaname = 'storage' and tablename = 'objects' and policyname = 'imagenes_lectura_publica') then
    create policy imagenes_lectura_publica on storage.objects
      for select using (bucket_id = 'imagenes');
  end if;

  if not exists (select 1 from pg_policies
                  where schemaname = 'storage' and tablename = 'objects' and policyname = 'imagenes_subida_con_sesion') then
    create policy imagenes_subida_con_sesion on storage.objects
      for insert to authenticated with check (bucket_id = 'imagenes');
  end if;
end $$;

-- ---------------------------------------------------------------------
-- 4) Para crear el primer administrador: registrarse en la aplicación y después ejecutar
--      update profiles set rol = 'admin' where email = 'tu-email@ejemplo.com';
--    Los empleados se asignan desde la pantalla "Empleados" del admin.
-- ---------------------------------------------------------------------
